version: '3.3'
services:
    application:
        container_name: normalizer_extension_bundle_app
        image: richcongress/php:7.3
        volumes:
            - .:/app:rw,cached
            - ~/.composer:/home/application/.composer:cached
